# Generated by Django 2.2 on 2019-04-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20181017_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasourcemember',
            name='access_token_secret',
        ),
        migrations.RemoveField(
            model_name='datasourcemember',
            name='twitter_id',
        ),
        migrations.AddField(
            model_name='datasourcemember',
            name='lastfm_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='datasourcemember',
            name='session_key',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='datasourcemember',
            name='last_submitted',
            field=models.DateTimeField(default='2019-04-11 19:22:47+00:00'),
        ),
        migrations.AlterField(
            model_name='datasourcemember',
            name='last_updated',
            field=models.DateTimeField(default='2019-04-11 19:22:47+00:00'),
        ),
    ]
