# Generated by Django 2.2 on 2019-04-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190418_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcemember',
            name='api_signature',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='datasourcemember',
            name='last_submitted',
            field=models.DateTimeField(default='2019-04-11 23:58:48+00:00'),
        ),
        migrations.AlterField(
            model_name='datasourcemember',
            name='last_updated',
            field=models.DateTimeField(default='2019-04-11 23:58:48+00:00'),
        ),
    ]
